#!/bin/sh

INIT_HOME=.

function get_proxy_pid {
  proxy_pid=`ps aux | grep -E '.*java.*proxy.*' | grep -v grep | awk '{print $2}'`
}

get_proxy_pid

if [ "$proxy_pid" == "" ]; then
  echo "Proxy is down"
  $INIT_HOME/proxy start

  get_proxy_pid

  if [ "$proxy_pid" == "" ]; then
    echo "Proxy panic"
    # posli mail alebo co
  fi
else
  echo "Proxy is up" 
fi
