#!/bin/sh
# Start/stop the adaptive proxy

PROXY_HOME=/home/proxy-user/proxy/AdaptiveProxy/trunk

test -f $PROXY_HOME/proxy.jar || (echo "proxy.jar not found" && exit 1)

function get_proxy_pid {
	proxy_pid=`ps aux | grep -E '.*java.*proxy.*' | grep -v grep | awk '{print $2}'`
	echo "PID = $proxy_pid"
}

function start_proxy {
	get_proxy_pid

	if [ "$proxy_pid" != "" ]; then
		log_action_msg "Proxy is already running"			
		return 1
	fi

	cd $PROXY_HOME
	java -jar proxy.jar &

	return $?
}

function stop_proxy {
	get_proxy_pid
	
	if [ "$proxy_pid" == "" ]; then
		log_daemon_msg "Proxy is not running"
		return 1
	fi

	kill $proxy_pid
	return $?
}

. /lib/lsb/init-functions

case "$1" in
start)	log_daemon_msg "Starting adaptive proxy server" "proxy"
				start_proxy
        log_end_msg $?
	;;
stop)	log_daemon_msg "Stopping adaptive proxy server" "proxy"
				stop_proxy
        log_end_msg $?
        ;;
restart) log_daemon_msg "Restarting adaptive proxy server" "proxy" 
				stop_proxy
				sleep 2
				start_proxy
        log_end_msg $?
        ;;
reload|force-reload) log_daemon_msg "Reloading configuration files for adaptive proxy server" "proxy"
	# proxy reloads automatically
        log_end_msg 0
        ;;
*)	log_action_msg "Usage: /etc/init.d/proxy {start|stop|restart|reload|force-reload}"
        exit 2 ;;
esac
exit 0
